### ISSUE TITLE
Nice Image Processing Application

### ISSUE THREAD

**Issue by htn274** [yimethan/computer_vision_study#1]
Thank you for your efforts. The application is very nice! 
I think it will be a good impression on your CV in the future. 
One point you can improve the app is about cropping feature. You can let the user use mouse instead of filling the form. Anyway it's just about user experience. 
Overall, you did it very well. Keep going on!

**Comment by yimethan** [comment]
Thank you so much!
I failed to figure out how to crop the image by dragging with mouse when building the application,
but I'll try to find a way to improve the cropping feature.
Thank you again 😄
